wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.10
    start_time: 1646145484
    t:
      1:
      - 2
      - 3
      - 5
      4: 3.9.10
      5: 0.12.10
      8:
      - 1
      - 3
      - 5
